version: '3.5'

services:

  mongo:
    container_name: 'alba-mongo' 
    image: mongo:4.2.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  dev:
    container_name: 'alba-environment' 
    build: .    
    volumes:
      - ./:/go/src/alba/cli
    depends_on:
      - mongo
    working_dir: /go/src/alba/cli


volumes:
  mongo_data: